### 1. 모든 상품 조회 (GET /products)
GET https://bagdaseul-sprint.onrender.com/products

### 2. 특정 조건으로 상품 조회 (GET /products?offset=0&limit=5&order=recent)
GET https://bagdaseul-sprint.onrender.com/products?offset=0&limit=5&order=recent

### 2-1. 특정 조건으로 상품 조회 (GET /products?search=고급)
GET https://bagdaseul-sprint.onrender.com/products?search=인기


### 3. 새로운 상품 생성 (POST /products)
POST https://bagdaseul-sprint.onrender.com/products
Content-Type: application/json

{
    "name": "고급 상품",
    "description": "이것은 새로 생성된 상품입니다.",
    "price": 25000,
    "tags": ["신상", "인기"]
}

### 4. 특정 상품 상세 조회 (GET /products/:id) - ID는 생성 후 확인
GET https://bagdaseul-sprint.onrender.com/products/a93e21e5-3d87-4a9e-a7fb-3af7a56b7486

### 5. 특정 상품 정보 수정 (PATCH /products/:id) - ID는 생성 후 확인
PATCH https://bagdaseul-sprint.onrender.com/products/a93e21e5-3d87-4a9e-a7fb-3af7a56b7486
Content-Type: application/json

{
    "price": 27000,
    "tags": ["할인", "재고정리"]
}

### 6. 특정 상품 삭제 (DELETE /products/:id) - ID는 생성 후 확인
# 아래 ID는 예시입니다. 실제 생성된 상품의 ID로 변경해야 합니다.
DELETE https://bagdaseul-sprint.onrender.com/products/dc7e9166-f8a5-4b5f-92b6-fcc4a64fced3





### 모든 Article 조회
GET https://bagdaseul-sprint.onrender.com/articles

### 2. 특정 조건으로 상품 조회 (GET /articles?offset=0&limit=5&order=recent)
GET https://bagdaseul-sprint.onrender.com/articles?offset=0&limit=5&order=recent

### 2-1. 특정 조건으로 상품 조회 (GET /articles?search=고급)
GET https://bagdaseul-sprint.onrender.com/articles?search=소식

### 새 Article 생성
POST https://bagdaseul-sprint.onrender.com/articles
Content-Type: application/json

{
  "title": "첫 번째 미션 제목",
  "content": "이것은 첫 번째 기사의 내용입니다. 아주 흥미로운 내용이죠."
}

### 특정 Article 조회 (ID 입력 필요)
GET https://bagdaseul-sprint.onrender.com/articles/0110fb13-b796-47e6-9bfd-c6481965dc8d


### Article 업데이트 (ID 입력 필요)
PATCH https://bagdaseul-sprint.onrender.com/articles/0110fb13-b796-47e6-9bfd-c6481965dc8d
Content-Type: application/json

{
  "title": "업데이트된 기사 제목",
  "content": "내용도 새롭게 변경되었습니다."
}

### Article 삭제 (ID 입력 필요)
DELETE https://bagdaseul-sprint.onrender.com/articles/0dcc73d7-d4ec-44cb-a403-87f56b7eb7b8






### 첫 번째 페이지 Product Comment 조회 (Product ID 입력 필요)
# 예시: GET {{baseUrl}}/products/YOUR_PRODUCT_ID/comments?take=5
GET https://bagdaseul-sprint.onrender.com/products/17e57d5a-8f91-41cf-a55e-b40353a46cdd/comments?take=5

### 다음 페이지 Product Comment 조회 (Product ID와 이전 응답의 nextCursor 값 입력 필요)
# 예시: GET {{baseUrl}}/products/YOUR_PRODUCT_ID/comments?take=5&cursor=NEXT_CURSOR_VALUE
GET https://bagdaseul-sprint.onrender.com/products/a26dd7c6-ed06-495c-bdf5-beea339f37d3/comments?take=5&cursor=99710df0-16bc-40f2-af0e-0aaa3483ba02

### 새 Product Comment 생성 (Product ID 입력 필요)
POST https://bagdaseul-sprint.onrender.com/products/17e57d5a-8f91-41cf-a55e-b40353a46cdd/comments
Content-Type: application/json

{
  "content": "이 제품에 대한 첫 번째 댓글입니다!"
}

### 특정 Product Comment 조회 (Product ID, Comment ID 입력 필요)
GET https://bagdaseul-sprint.onrender.com/products/a26dd7c6-ed06-495c-bdf5-beea339f37d3/comments/4b9f4006-acbc-4cae-822f-b0cad6e9ad75

### Product Comment 업데이트 (Product ID, Comment ID 입력 필요)
PATCH https://bagdaseul-sprint.onrender.com/products/a26dd7c6-ed06-495c-bdf5-beea339f37d3/comments/4b9f4006-acbc-4cae-822f-b0cad6e9ad75
Content-Type: application/json

{
  "content": "업데이트된 댓글 내용입니다1."
}

### Product Comment 삭제 (Product ID, Comment ID 입력 필요)
DELETE https://bagdaseul-sprint.onrender.com/products/1ca83f99-521c-4361-941d-adb4fe9154c3/comments/f2b2349d-ade8-462f-ba80-c574e93e0206






### 첫 번째 페이지 article Comment 조회 (article ID 입력 필요)
# 예시: GET {{baseUrl}}/articles/YOUR_article_ID/comments?take=5
GET https://bagdaseul-sprint.onrender.com/articles/de95f7e7-6460-40f6-a45f-7a8c0bfa2575/comments?take=5

### 다음 페이지 article Comment 조회 (article ID와 이전 응답의 nextCursor 값 입력 필요)
# 예시: GET {{baseUrl}}/articles/YOUR_article_ID/comments?take=5&cursor=NEXT_CURSOR_VALUE
GET https://bagdaseul-sprint.onrender.com/articles/de95f7e7-6460-40f6-a45f-7a8c0bfa2575/comments?take=5&cursor=99710df0-16bc-40f2-af0e-0aaa3483ba02

### 새 article Comment 생성 (article ID 입력 필요)
POST https://bagdaseul-sprint.onrender.com/articles/de95f7e7-6460-40f6-a45f-7a8c0bfa2575/comments
Content-Type: application/json

{
  "content": "이 제품에 대한 첫 번째 댓글입니다!"
}

### 특정 article Comment 조회 (article ID, Comment ID 입력 필요)
GET https://bagdaseul-sprint.onrender.com/articles/de95f7e7-6460-40f6-a45f-7a8c0bfa2575/comments/65da0a9f-d42d-4ab1-bf8b-2efb4cd8b87d

### article Comment 업데이트 (article ID, Comment ID 입력 필요)
PATCH https://bagdaseul-sprint.onrender.com/articles/de95f7e7-6460-40f6-a45f-7a8c0bfa2575/comments/65da0a9f-d42d-4ab1-bf8b-2efb4cd8b87d
Content-Type: application/json

{
  "content": "업데이트된 댓글 내용입니다."
}

### article Comment 삭제 (article ID, Comment ID 입력 필요)
DELETE https://bagdaseul-sprint.onrender.com/articles/71079d6e-0d77-4cc6-be2e-01c7688ce4ab/comments/ce9e8e3e-9a52-42b7-99c1-7f4caedb0a1b
