### 1. 모든 상품 조회 (GET /products)
GET http://localhost:3000/products

### 2. 특정 조건으로 상품 조회 (GET /products?offset=0&limit=5&order=recent)
GET http://localhost:3000/products?offset=0&limit=5&order=recent

### 3. 새로운 상품 생성 (POST /products)
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "고급 상품",
    "description": "이것은 새로 생성된 상품입니다.",
    "price": 25000,
    "tags": ["신상", "인기"]
}

### 4. 특정 상품 상세 조회 (GET /products/:id) - ID는 생성 후 확인
# 아래 ID는 예시입니다. 실제 생성된 상품의 ID로 변경해야 합니다.
GET http://localhost:3000/products/329cb45d-d91b-437a-a130-6e091f6e0096

### 5. 특정 상품 정보 수정 (PATCH /products/:id) - ID는 생성 후 확인
# 아래 ID는 예시입니다. 실제 생성된 상품의 ID로 변경해야 합니다.
PATCH http://localhost:3000/products/329cb45d-d91b-437a-a130-6e091f6e0096
Content-Type: application/json

{
    "price": 27000,
    "tags": ["할인", "재고정리"]
}

### 6. 특정 상품 삭제 (DELETE /products/:id) - ID는 생성 후 확인
# 아래 ID는 예시입니다. 실제 생성된 상품의 ID로 변경해야 합니다.
DELETE http://localhost:3000/products/329cb45d-d91b-437a-a130-6e091f6e0096


### 모든 Article 조회
GET http://localhost:3000/articles

### 2. 특정 조건으로 상품 조회 (GET /articles?offset=0&limit=5&order=recent)
GET http://localhost:3000/articles?offset=0&limit=5&order=recent

### 새 Article 생성
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "첫 번째 기사 제목",
  "content": "이것은 첫 번째 기사의 내용입니다. 아주 흥미로운 내용이죠."
}

### 특정 Article 조회 (ID 입력 필요)
GET http://localhost:3000/articles/0dcc73d7-d4ec-44cb-a403-87f56b7eb7b8


### Article 업데이트 (ID 입력 필요)
PATCH http://localhost:3000/articles/0dcc73d7-d4ec-44cb-a403-87f56b7eb7b8
Content-Type: application/json

{
  "title": "업데이트된 기사 제목",
  "content": "내용도 새롭게 변경되었습니다."
}

### Article 삭제 (ID 입력 필요)
DELETE http://localhost:3000/articles/0dcc73d7-d4ec-44cb-a403-87f56b7eb7b8
